services:
  ollama_agent:
    image: manzolo/ollama_documents_agent
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./static:/app/static